apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-javaapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xyz-javaapp
  template:
    metadata:
      labels:
        app: xyz-javaapp
    spec:
      containers:
      - name: xyz-javaapp
        image: ghostatlas14/xyz_javaapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: xyz-javaapp-service
spec:
  type: LoadBalancer
  selector:
    app: xyz-javaapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      
