- name: Configure Jenkins Master
  hosts: jenkins-master
  vars:
    ansible_ssh_private_key_file: /home/ec2-user/.ssh/devops_final.pem  # Path to your private key
    ansible_user: ec2-user                                  # SSH username
  tasks:
    # Update dnf packages
    - name: Update system packages
      dnf:
        update_cache: yes
      become: true
    # Install Jenkins
    - name: Install Jenkins
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
      become: true
    - name: Import Jenkins Key
      command: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      become: true
    - name: Upgrade system packages
      command: dnf upgrade -y
      become: true
    # Add required dependencies for the jenkins package
    - name: Install Java
      dnf:
        name:
          - fontconfig
          - java-17-amazon-corretto
        state: present
      become: true

    - name: Install Jenkins
      dnf:
        name: jenkins
        state: present
      become: true
    - name: Reload daemon 
      command: systemctl daemon-reload
      become: true
    # Start and Enable Jenkins
    - name: Enable Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
      become: true

- name: Configure Jenkins Worker
  hosts: jenkins-worker
  vars:
    ansible_ssh_private_key_file: /home/ec2-user/.ssh/devops_final.pem  # Path to your private key
    ansible_user: ec2-user                                  # SSH username
  tasks:
    # Update dnf packages
    - name: Update system packages
      dnf:
        update_cache: yes
      become: true
    # Install Jenkins
    - name: Install Jenkins
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
      become: true
    - name: Import Jenkins Key
      command: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      become: true
    - name: Upgrade system packages
      command: dnf upgrade -y
      become: true
    # Add required dependencies for the jenkins package
    - name: Install Java
      dnf: 
        name:
          - fontconfig
          - java-17-amazon-corretto
        state: present
      become: true
    - name: Install Jenkins
      dnf:
        name: jenkins
        state: present
      become: true
    - name: Reload daemon 
      command: systemctl daemon-reload
      become: true
    # Start and Enable Jenkins
    - name: Enable Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
      become: true     
